version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: last_mile_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  lmds-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/last_mile_delivery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root@1234
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
